/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apps40in_rosberry_test_grayimage_ImageUtil */

#ifndef _Included_com_apps40in_rosberry_test_newsapp_utils_ImageUtils
#define _Included_com_apps40in_rosberry_test_newsapp_utils_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apps40in_rosberry_test_grayimage_ImageUtil
 * Method:    ImgToGray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_apps40in_rosberry_test_newsapp_utils_ImageUtils_ImgToGray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
